<?php

namespace Tests\Feature;

use Tests\TestCase;

class Answer extends TestCase
{
    
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    public function testCreateNewQuestion()
    {

        $data = ["question" => "Est-ce que tu kiffes les tests ?", "category" => "test", "difficulty" => "1"];
        $this->post(route("questions.store", $data));
        $this->assertDatabaseHas("questions", $data);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
