<?php

namespace Tests\Feature;

use Tests\TestCase;

class AnswerTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    public function testCreateNewAnswer()
    {
        $data = ["name" => "Nooooooon", "is_valid" => "1", "category_id" => "" ];
        $this->post(route("questions.store", $data));
        $this->assertDatabaseHas("questions", $data);
    }


    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
