<?php

namespace Tests\Feature;

use App\Game;
use App\Http\Middleware\VerifyCsrfToken;
use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Tests\CreatesApplication;
use Tests\TestCase;
class GameTest extends TestCase
{
    use CreatesApplication, RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();
        $this->withoutMiddleware([VerifyCsrfToken::class]);
    }

    public function testCreateNewGame()
{
    $count_games = Game::count();

    $data = ["player1_name" => "Toto", "player2_name" => "Titi"];
    $this->post(route("games.store", $data));
    $this->assertDatabaseHas("users", ["name" => "Toto"]);
    $this->assertDatabaseHas("users", ["name" => "Titi"]);

    $this->assertEquals($count_games+1, Game::count());


}

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
