<?php

namespace Tests\Feature;

use App\Game;
use App\User;
use Tests\TestCase;

class GameTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    public function testCreateNewGame()
{
    $count_games = Game::count();

    $data = ["player1_name" => "Toto", "player2_name" => "Titi"];
    $this->post(route("games.store", $data));
    $this->assertDatabaseHas("users", ["name" => "Toto"]);
    $this->assertDatabaseHas("users", ["name" => "Titi"]);

    $this->assertEquals($count_games+1, Game::count());
}

    public function testAnswerQuestion() {


    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
