<?php

namespace Tests\Feature;

use App\Game;
use App\User;
use Tests\TestCase;

class QuestionTest extends TestCase
{

    private $game;
    private $player1;
    private $player2;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    public function testCreateNewQuestion()
    {

        $data = ["question" => "Est-ce que tu kiffes les tests ?", "category" => "test", "difficulty" => "1"];
        $this->post(route("questions.store", $data));
        $this->assertDatabaseHas("questions", $data);
    }

   protected function tearDown(): void
   {
       parent::tearDown(); // TODO: Change the autogenerated stub
   }

}
